connections:
  mysql:
    mioji_label:
      host: ""
      port: 3306
      username: ""
      password: ""
      database: ""
  redis:
    test:
      host: ""
      port: 6379
      username: ""
      password: ""
      db: 0
  mongodb:
    test1:
      uri: "mongodb://user:pass@ip:port/db"
params:
  test_params: "test_params"
